# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: swift
# cache: cocoapods
# podfile: Example/Podfile
before_install:
  # - gem install cocoapods # Since Travis is not always on latest version
  - ls -la
  - pod install --project-directory=Example
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list

script:
  - set -o pipefail && xcodebuild test -workspace Example/McPicker.xcworkspace -scheme McPicker-Example -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
